// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package no.ciber.mangekampen.model;

import no.ciber.mangekampen.model.Sesong;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Sesong_Roo_Configurable {
    
    declare @type: Sesong: @Configurable;
    
}
